services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./config:/opt/spark/work-dir/config
      - ./jobs:/opt/spark/work-dir/jobs
      - ./datasets:/opt/spark/work-dir/datasets
      - ./requirements.txt:/opt/spark/work-dir/requirements.txt
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - data_pipeline
    environment:
      - PYTHONPATH=/opt/spark/work-dir

  spark-worker: &worker
    container_name: spark-worker
    hostname: spark-worker
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./config:/opt/spark/work-dir/config
      - ./jobs:/opt/spark/work-dir/jobs
      - ./datasets:/opt/spark/work-dir/datasets
      - ./requirements.txt:/opt/spark/work-dir/requirements.txt
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
      PYTHONPATH: /opt/spark/work-dir
    networks:
      - data_pipeline

#  spark-worker-2:
#    <<: *worker
#
#  spark-worker-3:
#    <<: *worker
#
#  spark-worker-4:
#    <<: *worker
networks:
  data_pipeline:
    name: yelp_data_pipeline
    driver: bridge